apiVersion: v1
kind: Secret
metadata:
  name: stockshelf-secret
  namespace: stockshelf
type: Opaque
stringData:
  POSTGRES_PASSWORD: "stockshelf_pass"
  JWT_SECRET: "supersecretjwtkey_changeinproduction"
